package com.superqr.android.vision.v7.modem

import kotlin.math.ceil

object V7InnerFec {
    data class Plan(val channelBytes:Int,val parityBytes:Int,val dataBytes:Int,val blocks:List<Pair<Int,Int>>,val interleaveStride:Int)
    fun plan(channelBytes:Int,parityRatio:Double=V7ModemContract.DEFAULT_PARITY_RATIO):Plan{val parity=parityBytesForRatio(channelBytes,parityRatio);return Plan(channelBytes,parity,channelBytes-parity,balancedBlocks(channelBytes,parity),interleaveStride(channelBytes))}
    fun symbolPayloadCapacity(channelBytes:Int,parityRatio:Double=V7ModemContract.DEFAULT_PARITY_RATIO):Int{val capacity=plan(channelBytes,parityRatio).dataBytes-V7ModemContract.PACKET_OVERHEAD;if(capacity<1)throw V7ModemException("channel frame cannot fit a modem packet");return capacity}
    fun encode(logicalPacket:ByteArray,channelBytes:Int,parityRatio:Double=V7ModemContract.DEFAULT_PARITY_RATIO):ByteArray{
        val plan=plan(channelBytes,parityRatio);if(logicalPacket.size>plan.dataBytes)throw V7ModemException("logical packet exceeds inner-FEC data capacity");val padded=ByteArray(plan.dataBytes);logicalPacket.copyInto(padded);val codewords=ByteArray(channelBytes);var dataOffset=0;var codeOffset=0
        for((length,parity)in plan.blocks){val dataLength=length-parity;val encoded=V7ReedSolomon.encode(padded.copyOfRange(dataOffset,dataOffset+dataLength),parity);encoded.copyInto(codewords,codeOffset);dataOffset+=dataLength;codeOffset+=length}
        if(dataOffset!=padded.size||codeOffset!=channelBytes)throw IllegalStateException("inner FEC accounting error");return interleave(codewords,plan.interleaveStride)
    }
    fun decode(physicalFrame:ByteArray,parityRatio:Double=V7ModemContract.DEFAULT_PARITY_RATIO,erasedPhysicalBytes:IntArray=IntArray(0)):ByteArray{
        val plan=plan(physicalFrame.size,parityRatio);val erased=BooleanArray(plan.channelBytes);for(position in erasedPhysicalBytes){if(position !in erased.indices)throw V7ModemException("physical erasure outside frame");erased[position]=true};val raw=deinterleave(physicalFrame,plan.interleaveStride);val logicalErased=BooleanArray(plan.channelBytes)
        for(logical in 0 until plan.channelBytes){val physical=((logical.toLong()*plan.interleaveStride)%plan.channelBytes).toInt();logicalErased[logical]=erased[physical]}
        val out=ByteArray(plan.dataBytes);var codeOffset=0;var dataOffset=0
        for((length,parity)in plan.blocks){var count=0;for(i in 0 until length)if(logicalErased[codeOffset+i])count++;val erasures=IntArray(count);var cursor=0;for(i in 0 until length)if(logicalErased[codeOffset+i])erasures[cursor++]=i;val decoded=V7ReedSolomon.decode(raw.copyOfRange(codeOffset,codeOffset+length),parity,erasures);decoded.copyInto(out,dataOffset);codeOffset+=length;dataOffset+=decoded.size}
        return out
    }
    fun decodePacket(physicalFrame:ByteArray,parityRatio:Double=V7ModemContract.DEFAULT_PARITY_RATIO,erasedPhysicalBytes:IntArray=IntArray(0)):V7ModemPacket=V7ModemContract.parsePacket(decode(physicalFrame,parityRatio,erasedPhysicalBytes))
    fun balancedBlocks(channelBytes:Int,parityBytes:Int):List<Pair<Int,Int>>{if(channelBytes<2)throw V7ModemException("channel frame is too small");val blockCount=ceil(channelBytes/255.0).toInt();if(parityBytes !in blockCount..(channelBytes-blockCount))throw V7ModemException("invalid RS parity budget");val lb=channelBytes/blockCount;val le=channelBytes%blockCount;val pb=parityBytes/blockCount;val pe=parityBytes%blockCount;return List(blockCount){i->val length=lb+if(i<le)1 else 0;val parity=pb+if(i<pe)1 else 0;if(parity !in 1 until length)throw V7ModemException("invalid shortened RS block");length to parity}}
    fun parityBytesForRatio(channelBytes:Int,parityRatio:Double):Int{if(!(parityRatio>0.0&&parityRatio<1.0))throw V7ModemException("parity ratio must be between 0 and 1");val blocks=ceil(channelBytes/255.0).toInt();val requested=ceil(channelBytes*parityRatio).toInt();return minOf(channelBytes-blocks,maxOf(blocks,requested))}
    fun interleaveStride(channelBytes:Int):Int{if(channelBytes<2)throw V7ModemException("channel frame is too small");var stride=channelBytes/2+1;while(gcd(stride,channelBytes)!=1)stride++;return stride}
    private fun interleave(data:ByteArray,stride:Int):ByteArray{val out=ByteArray(data.size);for(logical in data.indices)out[((logical.toLong()*stride)%data.size).toInt()]=data[logical];return out}
    private fun deinterleave(data:ByteArray,stride:Int):ByteArray{val out=ByteArray(data.size);for(logical in data.indices)out[logical]=data[((logical.toLong()*stride)%data.size).toInt()];return out}
    private fun gcd(a0:Int,b0:Int):Int{var a=a0;var b=b0;while(b!=0){val t=a%b;a=b;b=t};return kotlin.math.abs(a)}
}

object V7ReedSolomon {
    private val exp=IntArray(512);private val log=IntArray(256);private val generators=HashMap<Int,IntArray>()
    init{var value=1;for(index in 0 until 255){exp[index]=value;log[value]=index;value=value shl 1;if(value and 0x100!=0)value=value xor 0x11D};for(index in 255 until 512)exp[index]=exp[index-255]}
    fun encode(message:ByteArray,parityBytes:Int):ByteArray{if(parityBytes !in 1..254||message.isEmpty()||message.size>255-parityBytes)throw V7ModemException("invalid shortened RS data length");val generator=generator(parityBytes);val work=IntArray(message.size+parityBytes);for(i in message.indices)work[i]=message[i].toInt()and 0xFF;for(i in message.indices){val coefficient=work[i];if(coefficient!=0)for(j in 1 until generator.size)work[i+j]=work[i+j] xor mul(generator[j],coefficient)};val out=ByteArray(work.size);message.copyInto(out);for(i in 0 until parityBytes)out[message.size+i]=work[message.size+i].toByte();return out}
    fun decode(codeword:ByteArray,parityBytes:Int,erasurePositions:IntArray=IntArray(0)):ByteArray{
        if(parityBytes !in 1 until codeword.size||codeword.size>255)throw V7ModemException("invalid shortened RS codeword");val erasures=erasurePositions.distinct().sorted();if(erasures.size>parityBytes)throw V7ModemException("too many RS erasures");if(erasures.any{it !in codeword.indices})throw V7ModemException("RS erasure outside codeword");val working=IntArray(codeword.size){codeword[it].toInt()and 0xFF};for(position in erasures)working[position]=0;val syndromes=syndromes(working,parityBytes);if(syndromes.all{it==0})return codeword.copyOfRange(0,codeword.size-parityBytes);val forney=forneySyndromes(syndromes,erasures,working.size);val errorLocator=findErrorLocator(forney,parityBytes,erasures.size);val errorPositions=findErrorPositions(errorLocator.reversedArray(),working.size);val positions=(erasures+errorPositions.toList()).distinct().sorted();val corrected=correctErrata(working,syndromes,positions);if(syndromes(corrected,parityBytes).any{it!=0})throw V7ModemException("RS codeword is not correctable");return ByteArray(codeword.size-parityBytes){corrected[it].toByte()}
    }
    private fun generator(parity:Int):IntArray=synchronized(generators){generators.getOrPut(parity){var result=intArrayOf(1);for(index in 0 until parity)result=polyMul(result,intArrayOf(1,pow(2,index)));result}}
    private fun mul(a:Int,b:Int):Int=if(a==0||b==0)0 else exp[log[a]+log[b]]
    private fun div(a:Int,b:Int):Int{if(b==0)throw ArithmeticException("GF divide by zero");return if(a==0)0 else exp[(log[a]-log[b]+255)%255]}
    private fun pow(a:Int,power:Int):Int=if(a==0)0 else exp[((log[a].toLong()*power).mod(255)).toInt()]
    private fun inverse(a:Int):Int{if(a==0)throw ArithmeticException("GF inverse zero");return exp[255-log[a]]}
    private fun polyScale(poly:IntArray,scalar:Int)=IntArray(poly.size){mul(poly[it],scalar)}
    private fun polyAdd(a:IntArray,b:IntArray):IntArray{val out=IntArray(maxOf(a.size,b.size));for(i in a.indices)out[i+out.size-a.size]=out[i+out.size-a.size] xor a[i];for(i in b.indices)out[i+out.size-b.size]=out[i+out.size-b.size] xor b[i];return out}
    private fun polyMul(a:IntArray,b:IntArray):IntArray{val out=IntArray(a.size+b.size-1);for(i in a.indices)if(a[i]!=0)for(j in b.indices)if(b[j]!=0)out[i+j]=out[i+j] xor mul(a[i],b[j]);return out}
    private fun polyEval(poly:IntArray,x:Int):Int{var value=poly[0];for(i in 1 until poly.size)value=mul(value,x) xor poly[i];return value}
    private fun syndromes(codeword:IntArray,parity:Int)=IntArray(parity+1){index->if(index==0)0 else polyEval(codeword,pow(2,index-1))}
    private fun errataLocator(coefficientPositions:List<Int>):IntArray{var locator=intArrayOf(1);for(position in coefficientPositions)locator=polyMul(locator,intArrayOf(pow(2,position),1));return locator}
    private fun errorEvaluator(reversedSyndromes:IntArray,locator:IntArray,degree:Int):IntArray{val product=polyMul(reversedSyndromes,locator);return product.copyOfRange(product.size-degree-1,product.size)}
    private fun forneySyndromes(syndromes:IntArray,erasures:List<Int>,codewordLen:Int):IntArray{val out=syndromes.copyOfRange(1,syndromes.size).toMutableList();for(position in erasures){val x=pow(2,codewordLen-1-position);for(i in 0 until out.size-1)out[i]=mul(out[i],x) xor out[i+1];out.removeAt(out.lastIndex)};return out.toIntArray()}
    private fun findErrorLocator(syndromes:IntArray,parity:Int,erasureCount:Int):IntArray{var locator=intArrayOf(1);var oldLocator=intArrayOf(1);val shift=maxOf(0,syndromes.size-parity);for(index in 0 until parity-erasureCount){val syndromeIndex=index+shift;var delta=syndromes[syndromeIndex];for(coefficient in 1 until locator.size)delta=delta xor mul(locator[locator.size-coefficient-1],syndromes[syndromeIndex-coefficient]);oldLocator=oldLocator+0;if(delta!=0){if(oldLocator.size>locator.size){val newLocator=polyScale(oldLocator,delta);oldLocator=polyScale(locator,inverse(delta));locator=newLocator};locator=polyAdd(locator,polyScale(oldLocator,delta))}};var first=0;while(first<locator.lastIndex&&locator[first]==0)first++;locator=locator.copyOfRange(first,locator.size);val errors=locator.size-1;if(errors*2+erasureCount>parity)throw V7ModemException("RS correction capacity exceeded");return locator}
    private fun findErrorPositions(locator:IntArray,codewordLen:Int):IntArray{val expected=locator.size-1;val positions=ArrayList<Int>(expected);for(index in 0 until codewordLen)if(polyEval(locator,pow(2,index))==0)positions+=codewordLen-1-index;if(positions.size!=expected)throw V7ModemException("RS error positions could not be located");return positions.toIntArray()}
    private fun correctErrata(codeword:IntArray,syndromes:IntArray,positions:List<Int>):IntArray{if(positions.isEmpty())return codeword;val coefficients=positions.map{codeword.size-1-it};val locator=errataLocator(coefficients);val evaluator=errorEvaluator(syndromes.reversedArray(),locator,locator.size-1).reversedArray();val roots=coefficients.map{pow(2,-(255-it))};val corrections=IntArray(codeword.size);for(index in roots.indices){val inverseRoot=inverse(roots[index]);var derivative=1;for(other in roots.indices)if(other!=index)derivative=mul(derivative,1 xor mul(inverseRoot,roots[other]));if(derivative==0)throw V7ModemException("invalid RS locator derivative");var numerator=polyEval(evaluator.reversedArray(),inverseRoot);numerator=mul(roots[index],numerator);corrections[positions[index]]=div(numerator,derivative)};return polyAdd(codeword,corrections)}
}
